
# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: "https://infonetlijian.github.io/Blog_demo/"
url: "https://infonetlijian.github.io/Blog_demo/"
date_format: "ordinal"
title:        李健的博客
tagline:      欢迎来到通信攻城狮的世界
subtitle: "欢迎来到通信攻城狮的世界"
description: "李健的博客"
keywords: 李健的博客
favicon: /favicon.ico
timezone: Asia/Hefei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
name:       Mr.Cheng
url:        https://infonetlijian.github.io/Blog_demo/
organization: ustc
organization_url: http://if.ustc.edu.cn
github_username: infonetlijian
location: Hefei, China
email: lijian9@mail.ustc.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /posts/
    label: 博文

  -
    href: /photos/
    label: 图片


# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
#     - jekyll-html-pipeline
    - jekyll-paginate

# ---------------- #
#     Disqus       #
# ---------------- #
disqus: true
disqus_shortname: NathenDrake
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-101909927-1